  # prod-deploy.yml
  # master branch 로 pull request 가 merge 되었을 때 실행됨
  name: Deploy to EC2

  on:
    push:
      branches:
        - master
        - develop

  permissions:
    id-token: write
    contents: read

  jobs:
    deploy:
      name: deploy
      runs-on: ubuntu-latest
      environment: production

      steps:
        - name: check out the code
          uses: actions/checkout@v3

        - name: setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '22'

        - name: cache node modules
          uses: actions/cache@v3
          id: cache
          with:
            path: node_modules
            key: npm-packages-${{ hashFiles('./package-lock.json') }}

        - name: install dependencies
          if: steps.cache.outputs.cache-hit != 'true'
          run: npm install
          working-directory: ./

        - name: run build
          run: npm run build

        - name: run tests
          run: npm run test

        - name: generate swagger documentation
          run: npm run docs

        - name: convert swagger documentation to postman collection
          run: npm run docs-convert

        - name: upload to postman
          env:
            POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
            POSTMAN_COLLECTION_ID: ${{ secrets.POSTMAN_COLLECTION_ID }}
          run: |
            POSTMAN_JSON_PATH="./docs/postman-output.json"

            curl -X PUT \
              "https://api.getpostman.com/collections/$POSTMAN_COLLECTION_ID" \
              -H "X-Api-Key: $POSTMAN_API_KEY" \
              -H "Content-Type: application/json" \
              --data @$POSTMAN_JSON_PATH

        - name: compress file
          run: tar -czf dev-api.tar.gz dist/ node_modules/ src/ Dockerfile package-lock.json package.json

        - name: configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            role-to-assume: ${{ secrets.AWS_GITHUB_DEPLOY_ROLE}}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: upload to S3
          run: |
            aws s3 cp dev-api.tar.gz s3://${{ secrets.S3_BUCKET_NAME }}/dev-api.tar.gz

        - name: deploy using SSM
          run: |
              aws ssm send-command --document-name "AWS-RunShellScript" \
                --targets "Key=instanceIds,Values=${{ secrets.EC2_INSTANCE_ID }}" \
                --parameters 'commands=["aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/dev-api.tar.gz /home/ec2-user/docker-nginx-web/dev-api/dev-api.tar.gz", "cd /home/ec2-user/docker-nginx-web/dev-api", "tar --overwrite -xzf dev-api.tar.gz", "sudo rm -rf dev-api.tar.gz", "docker-compose down dev-api-server", "docker-compose up -d --build dev-api-server"]' \
                --comment "Deploying dist with dev-api.tar.gz" \
                --region ${{ secrets.AWS_REGION }}